{% set version = "9.13.0" %}

package:
  name: medcoupling
  version: '{{ version }}'

source:
  - fn: 'medcoupling_{{ version }}.tar.gz'
    url: https://github.com/SalomePlatform/medcoupling/archive/refs/tags/V{{ version.replace('.', '_') }}.tar.gz
    sha256: 54d010df0d8a66c7cf7b39a40e28aac16bc0bc20faf97c5190d0a2df4941e15e
  - fn: 'config_{{ version }}.tar.gz'
    url: https://github.com/SalomePlatform/configuration/archive/refs/tags/V{{ version.replace('.', '_') }}.tar.gz
    sha256: b0bb296536cefb3b5e063a57fab8b66b510ff76d766fbd462ee10dedac3c4872
    folder: deps/config


build:
  skip: true  # [osx]
  detect_binary_files_with_prefix: true
  # string: py{{ CONDA_PY }}_mpi_{{ mpi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}   # [mpi != "nompi"]
  # string: py{{ CONDA_PY }}_nompi_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}           # [mpi == "nompi"]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make                                      # [not win]
    - ninja                                     # [win]
    - cmake<4
    - swig >=4.0.2

  host:
    - python
    - numpy<2
    - libboost-devel
    - zlib
    - hdf5
    - libxml2
    - libmed
    - petsc                                     # [mpi != 'nompi']
    - {{ mpi }}                                 # [mpi != 'nompi']

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}                                 # [mpi != 'nompi']

test:
  imports:
    - medcoupling
    - MEDRenumber
    - MEDCouplingRemapper
    - MEDLoader
    - MEDPartitioner
    - MEDCoupling  # [linux]
    - MEDCouplingCompat  # [win or osx]

about:
  home: https://git.salome-platform.org/gitweb/?p=tools/medcoupling.git
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'The MEDCoupling tool gathers several powerful functionalities around the input and output data of simulation codes (meshes and fields mainly)'
  description: |
    The MEDCoupling tool gathers several powerful functionalities around the input and output data of simulation codes (meshes and fields mainly)
  doc_url: https://docs.salome-platform.org/latest/dev/MEDCoupling/developer/index.html
  dev_url: https://git.salome-platform.org/gitweb/?p=tools/medcoupling.git;a=summary

extra:
  recipe-maintainers:
    - Krande
